[assembly:System.Reflection.AssemblyTitle("Managed Debugger Sample")] 
[assembly:System.Reflection.AssemblyCompany("Microsoft Corporation")] 
[assembly:System.Reflection.AssemblyCopyright("Copyright © Microsoft Corporation.  All rights reserved.")] 
[assembly:System.Reflection.AssemblyTrademark("Microsoft® is a registered trademark of Microsoft Corporation.")] 
[assembly:System.Reflection.AssemblyVersion("2.0.0")] 
